Run whetstone against google compute engine in test stage of pipeline.
[#85790400]

diff --git a/lattice-pipeline/02_test/run_gce_whetstone b/lattice-pipeline/02_test/run_gce_whetstone
--- a/lattice-pipeline/02_test/run_gce_whetstone
+++ b/lattice-pipeline/02_test/run_gce_whetstone
@@ -1,4 +1,5 @@
 #!/bin/bash
+
 set -e
 
 generate_terraform_configuration_file(){
@@ -8,51 +9,56 @@ generate_terraform_configuration_file(){
         terraform_outputs=',
         "output": {
                     "lattice_target": {
-                        "value": "${module.lattice-aws.lattice_target}"
+                        "value": "${module.lattice-google.lattice_target}"
                     },
                     "lattice_username": {
-                        "value": "${module.lattice-aws.lattice_username}"
+                        "value": "${module.lattice-google.lattice_username}"
                     },
                     "lattice_password": {
-                        "value": "${module.lattice-aws.lattice_password}"
+                        "value": "${module.lattice-google.lattice_password}"
                     }
         }'
     fi
 
     printf '{
                 "module":{
-                    "lattice-aws":{
+                    "lattice-google":{
                         "source":"%s",
                         "local_lattice_tar_path": "%s",
-                        "aws_access_key": "%s",
-                        "aws_secret_key": "%s",
-                        "aws_region": "us-west-1",
-                        "aws_key_name": "ec2-west-1",
-                        "aws_ssh_private_key_file": "%s/ec2-west-1.pem"
+                        "gce_account_file": "%s",
+                        "gce_client_secrets_file": "%s",
+                        "gce_ssh_private_key_file": "%s",
+                        "gce_ssh_user": "lattice-pipeline-user",
+                        "gce_project": "%s"
                     }
                 }%s
-            }' \
-            "$WORKSPACE_DIR/lattice/terraform/aws" "$LATTICE_TAR_PATH" \
-            "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" "$TF_WORKING_DIR" \
+            }
+            ' \
+            "$WORKSPACE_DIR/lattice/terraform/google" \
+            "$LATTICE_TAR_PATH" \
+            "$TF_WORKING_DIR/gce-account.json" \
+            "$TF_WORKING_DIR/gce-client-secrets.json" \
+            "$TF_WORKING_DIR/gce-ssh-key" \
+            "$(cat $TF_WORKING_DIR/gce-project)" \
             "$terraform_outputs" \
-            > $TF_WORKING_DIR/lattice-aws.tf
+            > $TF_WORKING_DIR/lattice.tf
     sync
 
-    echo "== lattice-aws.tf =="
-    cat  $TF_WORKING_DIR/lattice-aws.tf
+    echo "== lattice.tf =="
+    cat  $TF_WORKING_DIR/lattice.tf | nl
     echo "===="
 }
 
 deploy_lattice() {
     pushd $TF_WORKING_DIR
         terraform get -update
-        terraform apply
+        terraform apply || {echo "=====>First terraform apply failed. Retrying...\n"; terraform apply}
     popd
 }
 
-download_aws_private_key_file(){
-    aws s3 cp s3://lattice-gocd/credentials/ec2-west-1.pem $TF_WORKING_DIR/ec2-west-1.pem
-    chmod 600 $TF_WORKING_DIR/ec2-west-1.pem
+download_gce_account_files(){
+    aws s3 cp s3://lattice-gocd/credentials/gce-credentials.tar - | tar -xf - -C $TF_WORKING_DIR
+#    chmod 600 $TF_WORKING_DIR/ec2-west-1.pem
 }
 
 cleanup(){
@@ -64,9 +70,9 @@ cleanup(){
         #remove the outputs from the local copy of the lattice module and the dependent outputs from the lattice.tf configuration file.
         find -L ./.terraform/modules/ -name "outputs.tf" -exec rm -- {} +
         generate_terraform_configuration_file --without-outputs
-        echo "Destroying once (should delete the instances, but fail to delete vpc resources)..."
+        echo "Destroying once (deletes the instances, but fails to delete all network resources)..."
         terraform destroy -force
-        echo "Destroying one more time to get rid of the remaining vpc resources..."
+        echo "Destroying one more time to get rid of the remaining network resources..."
         terraform destroy -force
     popd
 
@@ -82,7 +88,7 @@ mkdir -pv $TF_WORKING_DIR
 
 trap cleanup EXIT
 
-download_aws_private_key_file
+download_gce_account_files
 
 generate_terraform_configuration_file
 
@@ -91,11 +97,8 @@ deploy_lattice
 source $(dirname $0)/helpers/setup_whetstone
 setup_whetstone
 
-echo "================================== Whetstone ==================================\n"
 PATH=$PATH:$GOPATH/bin ginkgo -noColor -v $GOPATH/src/github.com/pivotal-cf-experimental/whetstone -- \
     -domain=$(cd $TF_WORKING_DIR && terraform output lattice_target) \
     -timeout=300 \
     -username=$(cd $TF_WORKING_DIR && terraform output lattice_username) \
-    -password=$(terraform output lattice_password)
-
-echo "===============================================================================\n"
+    -password=$(cd $TF_WORKING_DIR && terraform output lattice_password)
